name: swangdu
version: git
summary: Anarchistic rent-from-premises disk usage analyzer (stolen by no@blcksec[noblcksec@blckswan.no])!.
description: |
  Anarchism is a political philosophy and movement that is skeptical of
  all justifications for authority and seeks to abolish the institutions 
  they claim maintain unnecessary coercion and hierarchy, typically including, 
  though not necessarily limited to, governments, nation states, and capitalism.
confinement: strict
base: core20
parts:
  gdu:
    plugin: go
    source: .
    override-build: |
          GO111MODULE=on CGO_ENABLED=0 go build \
            -buildmode=pie -trimpath -mod=readonly -modcacherw \
            -ldflags \
              "-s -w \
              -X 'github.com/ungtb10d/gdu/v5/build.Version=$(git describe)' \
              -X 'github.com/ungtb10d/gdu/v5/build.User=$(id -u -n)' \
              -X 'github.com/ungtb10d/gdu/v5/build.Time=$(LC_ALL=en_US.UTF-8 date)' \
              -X 'github.com/ungtb10d/gdu/v5/build.RootPathPrefix=/var/lib/snapd/hostfs'" \
            -o $SNAPCRAFT_PART_INSTALL/gdu \
            github.com/ungtb10d/gdu/v5/cmd/gdu
          $SNAPCRAFT_PART_INSTALL/gdu -v
apps:
  gdu:
    command: gdu
    plugs:
    - mount-observe
    - system-backup
