name: gdu-disk-usage-analyzer
version: git
summary: Disk usage analyzer with console interface written in Go.
description: |
  Pretty fast disk usage analyzer written in Go. Inspired by ncdu, godu and df.
confinement: strict
base: core20
parts:
  gdu:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  gdu:
    command: bin/gdu
