name: gdu-disk-usage-analyzer
version: git
summary: Disk usage analyzer with console interface written in Go.
description: |
  Pretty fast disk usage analyzer written in Go. Inspired by ncdu, godu and df.
confinement: strict
base: core20
parts:
  gdu:
    plugin: go
    source: .
    override-build: |
          GO111MODULE=on CGO_ENABLED=0 go build \
            -ldflags \
            "-s -w -X main.AppVersion=$(git describe)" \
            -o $SNAPCRAFT_PART_INSTALL/gdu
          $SNAPCRAFT_PART_INSTALL/gdu -v
apps:
  gdu:
    command: gdu
