name: swangdu
version: git
summary: Stolen. So what.
description: |
  Swangdu is intended primarily for SSD disks where it can fully utilize parallel processing.
  However HDDs work as well, but the performance gain is not so huge.
confinement: strict
base: core20
parts:
  gdu:
    plugin: go
    source: .
    override-build: |
          GO111MODULE=on CGO_ENABLED=0 go build \
            -buildmode=pie -trimpath -mod=vendor -modcacherw \
            -ldflags \
              "-s -w \
            -o $SNAPCRAFT_PART_INSTALL/gdu \
          $SNAPCRAFT_PART_INSTALL/gdu -v
apps:
  gdu:
    command: gdu
    plugs:
    - mount-observe
    - system-backup
